"""
player.py
---------
The Player class: handles position, movement input, collision with
the world, and a tiny 2-frame walk animation.
"""

import pygame
from settings import TILE_SIZE, PLAYER_SPEED


class Player:
    def __init__(self, x, y):
        # Position is stored as floats (in world pixels) so slow speeds
        # like 1.5 px/frame don't get rounded away to 0.
        self.x = float(x)
        self.y = float(y)

        # Load the sprite sheet generated by assets_gen.py.
        # It's 16x32: frame 0 (standing) on top, frame 1 (walking) below.
        sheet = pygame.image.load("assets/sprite01.png").convert_alpha()
        self.frames = {
            "stand": sheet.subsurface(pygame.Rect(0, 0, TILE_SIZE, TILE_SIZE)),
            "walk": sheet.subsurface(pygame.Rect(0, TILE_SIZE, TILE_SIZE, TILE_SIZE)),
        }
        self.facing_left = False

        # Animation timing
        self.anim_timer = 0.0
        self.anim_speed = 0.12  # seconds per frame swap
        self.current_frame = "stand"

    @property
    def width(self):
        return TILE_SIZE

    @property
    def height(self):
        return TILE_SIZE

    def get_rect(self):
        """A pygame Rect representing the player's position/size, for collisions."""
        return pygame.Rect(int(self.x), int(self.y), self.width, self.height)

    def handle_input(self, keys, dt, world):
        """
        Read arrow keys / WASD, figure out the desired movement, then
        move axis-by-axis - checking collisions separately for X and Y.
        Moving one axis at a time lets the player slide along walls
        instead of getting fully stuck when bumping a corner.
        """
        dx = dy = 0.0
        if keys[pygame.K_LEFT] or keys[pygame.K_a]:
            dx -= PLAYER_SPEED
        if keys[pygame.K_RIGHT] or keys[pygame.K_d]:
            dx += PLAYER_SPEED
        if keys[pygame.K_UP] or keys[pygame.K_w]:
            dy -= PLAYER_SPEED
        if keys[pygame.K_DOWN] or keys[pygame.K_s]:
            dy += PLAYER_SPEED

        moving = dx != 0 or dy != 0

        if dx < 0:
            self.facing_left = True
        elif dx > 0:
            self.facing_left = False

        # --- Move on X axis, then check collision ---
        if dx != 0:
            new_x = self.x + dx
            if not self._collides(new_x, self.y, world):
                self.x = new_x

        # --- Move on Y axis, then check collision ---
        if dy != 0:
            new_y = self.y + dy
            if not self._collides(self.x, new_y, world):
                self.y = new_y

        self._update_animation(dt, moving)

    def _collides(self, new_x, new_y, world):
        """
        Check whether placing the player's rect at (new_x, new_y) would
        overlap a solid tile. We check all 4 corners of the player's box.
        """
        rect = pygame.Rect(int(new_x), int(new_y), self.width, self.height)
        corners = [
            (rect.left, rect.top),
            (rect.right - 1, rect.top),
            (rect.left, rect.bottom - 1),
            (rect.right - 1, rect.bottom - 1),
        ]
        return any(world.is_solid_pixel(cx, cy) for cx, cy in corners)

    def _update_animation(self, dt, moving):
        if not moving:
            self.current_frame = "stand"
            self.anim_timer = 0.0
            return

        self.anim_timer += dt
        if self.anim_timer >= self.anim_speed:
            self.anim_timer = 0.0
            self.current_frame = "walk" if self.current_frame == "stand" else "stand"

    def draw(self, surface, camera_x, camera_y):
        image = self.frames[self.current_frame]
        if self.facing_left:
            image = pygame.transform.flip(image, True, False)
        screen_x = self.x - camera_x
        screen_y = self.y - camera_y
        surface.blit(image, (screen_x, screen_y))
